package edu.dlnu.oa.dept.pojo;

import java.io.Serializable;

public class Dept implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.id
     *
     * @mbggenerated
     */
    private Integer deptId;

    public Dept(Integer deptId, String deptName, String deptLoc, String deptIntro) {
        this.deptId = deptId;
        this.deptName = deptName;
        this.deptLoc = deptLoc;
        this.deptIntro = deptIntro;
    }

    public Dept(String deptName, String deptLoc, String deptIntro) {
        this.deptName = deptName;
        this.deptLoc = deptLoc;
        this.deptIntro = deptIntro;
    }

    public Dept() {
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.address
     *
     * @mbggenerated
     */
    private String deptLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.describe
     *
     * @mbggenerated
     */
    private String deptIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dept
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.id
     *
     * @return the value of dept.id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.id
     *
     * @param deptId the value for dept.id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.name
     *
     * @return the value of dept.name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.name
     *
     * @param deptName the value for dept.name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.address
     *
     * @return the value of dept.address
     *
     * @mbggenerated
     */
    public String getDeptLoc() {
        return deptLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.address
     *
     * @param deptLoc the value for dept.address
     *
     * @mbggenerated
     */
    public void setDeptLoc(String deptLoc) {
        this.deptLoc = deptLoc == null ? null : deptLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.describe
     *
     * @return the value of dept.describe
     *
     * @mbggenerated
     */
    public String getDeptIntro() {
        return deptIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.describe
     *
     * @param deptIntro the value for dept.describe
     *
     * @mbggenerated
     */
    public void setDeptIntro(String deptIntro) {
        this.deptIntro = deptIntro == null ? null : deptIntro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(deptId);
        sb.append(", name=").append(deptName);
        sb.append(", address=").append(deptLoc);
        sb.append(", describe=").append(deptIntro);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}