package edu.dlnu.oa.emp.pojo;

import java.io.Serializable;
import java.util.Date;

public class Emp implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.dept_id
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.job_id
     *
     * @mbggenerated
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.birthday
     *
     * @mbggenerated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.hiredate
     *
     * @mbggenerated
     */
    private Date hiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.qq
     *
     * @mbggenerated
     */
    private Integer qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.salary
     *
     * @mbggenerated
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table emp
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.name
     *
     * @return the value of emp.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.name
     *
     * @param name the value for emp.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.login_name
     *
     * @return the value of emp.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.login_name
     *
     * @param loginName the value for emp.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.dept_id
     *
     * @return the value of emp.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.dept_id
     *
     * @param deptId the value for emp.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.job_id
     *
     * @return the value of emp.job_id
     *
     * @mbggenerated
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.job_id
     *
     * @param jobId the value for emp.job_id
     *
     * @mbggenerated
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.gender
     *
     * @return the value of emp.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.gender
     *
     * @param gender the value for emp.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.email
     *
     * @return the value of emp.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.email
     *
     * @param email the value for emp.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.birthday
     *
     * @return the value of emp.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.birthday
     *
     * @param birthday the value for emp.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.hiredate
     *
     * @return the value of emp.hiredate
     *
     * @mbggenerated
     */
    public Date getHiredate() {
        return hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.hiredate
     *
     * @param hiredate the value for emp.hiredate
     *
     * @mbggenerated
     */
    public void setHiredate(Date hiredate) {
        this.hiredate = hiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.tel
     *
     * @return the value of emp.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.tel
     *
     * @param tel the value for emp.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.qq
     *
     * @return the value of emp.qq
     *
     * @mbggenerated
     */
    public Integer getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.qq
     *
     * @param qq the value for emp.qq
     *
     * @mbggenerated
     */
    public void setQq(Integer qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.title
     *
     * @return the value of emp.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.title
     *
     * @param title the value for emp.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.salary
     *
     * @return the value of emp.salary
     *
     * @mbggenerated
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.salary
     *
     * @param salary the value for emp.salary
     *
     * @mbggenerated
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", loginName=").append(loginName);
        sb.append(", deptId=").append(deptId);
        sb.append(", jobId=").append(jobId);
        sb.append(", gender=").append(gender);
        sb.append(", email=").append(email);
        sb.append(", birthday=").append(birthday);
        sb.append(", hiredate=").append(hiredate);
        sb.append(", tel=").append(tel);
        sb.append(", qq=").append(qq);
        sb.append(", title=").append(title);
        sb.append(", salary=").append(salary);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public Emp() {
    }

    public Emp(String name, String loginName, Integer deptId, Integer jobId, String gender) {
        this.name = name;
        this.loginName = loginName;
        this.deptId = deptId;
        this.jobId = jobId;
        this.gender = gender;
    }

    public Emp(String name, String loginName, Integer deptId, Integer jobId, String gender, String email, Date birthday, Date hiredate, String tel, Integer qq, String title, Integer salary) {
        this.name = name;
        this.loginName = loginName;
        this.deptId = deptId;
        this.jobId = jobId;
        this.gender = gender;
        this.email = email;
        this.birthday = birthday;
        this.hiredate = hiredate;
        this.tel = tel;
        this.qq = qq;
        this.title = title;
        this.salary = salary;
    }

    public Emp(Integer id, String name, String loginName, Integer deptId, Integer jobId, String gender, String email, Date birthday, Date hiredate, String tel, Integer qq, String title, Integer salary) {
        this.id = id;
        this.name = name;
        this.loginName = loginName;
        this.deptId = deptId;
        this.jobId = jobId;
        this.gender = gender;
        this.email = email;
        this.birthday = birthday;
        this.hiredate = hiredate;
        this.tel = tel;
        this.qq = qq;
        this.title = title;
        this.salary = salary;
    }
}